### ISSUE TITLE
Publish on modrinth and/or curseforge

### ISSUE THREAD

**Issue by Paul1365972** [andrewzah/i-am-very-smart#1]
It would be great to actually publish this fork (maybe under a new or derived name) as the original developer does not maintain the project anymore.
Should be relatively fast and easy on modrinth at least.

**Comment by andrewzah** [comment]
To be honest, I don't have the time or interest currently to maintain a fork of i-am-very-smart. I'm not very familiar with java either, this was more of a one time thing for the server that I run.

**Comment by Paul1365972** [comment]
No problem, maybe ill revisit this some day (probably not)
